version: 2

references:
  js_deps_cache_key: &js_deps_cache_key
    v8-dependency-js-deps-{{ checksum "package-lock.json" }}
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.15
      - image: mongo:3.4.19-jessie
    steps:
      - *attach_workspace
      - checkout
      - restore_cache:
          keys:
            - *js_deps_cache_key
      - run: npm install
      - save_cache:
          key: *js_deps_cache_key
          paths:
            - node_modules
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:10.15
      - image: mongo:3.4.19-jessie
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Test
          command: npm run test

  test-integration:
    docker:
      - image: circleci/node:10.15
      - image: mongo:3.4.19-jessie
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Test integration
          command: npm run test:e2e

workflows:
  version: 2
  cicd:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-integration:
          requires:
            - build
